services:
  cheat-sheet-tex:
    build:
      context: image
      target: cheat-sheet
      cache_from:
        - ghcr.io/${REPO_OWNER:-bacluc}/fund-data-science-cheat-sheet:${VERSION:-local}
    image: ghcr.io/${REPO_OWNER:-bacluc}/fund-data-science-cheat-sheet:${VERSION:-local}
    volumes:
      - ./tex:/workspace
      - ./out:/out
